dependencies:
    "ansible.netcommon": "*"
description: ''
documentation: ''
homepage: ''
issues: ''
license: "Apache-2.0"
name: aos_switch
namespace: arubanetworks
readme: README.md
repository: https://github.com/aruba/aos-switch-ansible-collection
tags: [
  networking,
  aruba,
  switch,
  switches,
  hpe,
  datacenter
]
version: 1.6.0
authors:
  - "Ti Chiapuzio-Wong"
  - "Sunil Veeramachaneni"
  - "Castro, Jorge Arturo"
  - "Emimal T"
